import type { SeasonOntology } from '@/lib/ontology/types';

export const SEASON_3_SCI_FI_ONTOLOGY: SeasonOntology = {
  seasonId: 'season-3',
  seasonSlug: 'sci-fi',
  taxonomyVersion: 'season-3-sci-fi-v1',
  nodes: [
    {
      slug: 'proto-science-fiction',
      name: 'Proto Science Fiction',
      description: 'Early speculative cinema foundations from silent-era futurism through pre-space-age thought experiments.',
      canonicalThemes: ['industrial modernity', 'scientific hubris', 'future societies'],
      commonKeywords: ['silent', 'futurist', 'mad scientist', 'automaton', 'utopia', 'metropolis'],
      negativeSignals: ['pure contemporary action franchise', 'historical drama without speculative premise'],
      typicalEra: ['1900s', '1910s', '1920s', '1930s'],
    },
    {
      slug: 'space-opera',
      name: 'Space Opera',
      description: 'Large-scale interstellar adventure centered on galactic conflict, exploration, and mythic heroics.',
      canonicalThemes: ['interstellar conflict', 'galactic politics', 'space adventure'],
      commonKeywords: ['galaxy', 'starship', 'empire', 'rebellion', 'planetary'],
      negativeSignals: ['single-location domestic drama', 'non-speculative period piece'],
    },
    {
      slug: 'hard-science-fiction',
      name: 'Hard Science Fiction',
      description: 'Speculative narratives grounded in scientific plausibility, engineering constraints, or research procedure.',
      canonicalThemes: ['scientific method', 'systems failure', 'mission realism'],
      commonKeywords: ['astronaut', 'orbital', 'physics', 'mission', 'experiment', 'simulation'],
      negativeSignals: ['pure fantasy cosmology', 'magic-first worldbuilding'],
    },
    {
      slug: 'cyberpunk',
      name: 'Cyberpunk',
      description: 'High-tech / low-life futures focused on networked systems, corporate power, and urban decay.',
      canonicalThemes: ['corporate dystopia', 'networked identity', 'augmented bodies'],
      commonKeywords: ['cyberpunk', 'hacker', 'megacorp', 'cyberspace', 'neon', 'implant'],
      negativeSignals: ['pastoral rural setting without technological mediation', 'historical costume drama'],
      typicalEra: ['1980s', '1990s', '2000s'],
    },
    {
      slug: 'dystopian-science-fiction',
      name: 'Dystopian Science Fiction',
      description: 'Authoritarian or structurally oppressive futures exploring control, conformity, and resistance.',
      canonicalThemes: ['state control', 'surveillance', 'social stratification'],
      commonKeywords: ['dystopia', 'authoritarian', 'surveillance', 'oppression', 'resistance'],
      negativeSignals: ['optimistic exploratory adventure', 'non-speculative slice of life'],
    },
    {
      slug: 'post-apocalyptic-science-fiction',
      name: 'Post-Apocalyptic Science Fiction',
      description: 'After-collapse futures concerned with survival, resource scarcity, and societal reconstruction.',
      canonicalThemes: ['civilization collapse', 'scarcity', 'survival ethics'],
      commonKeywords: ['wasteland', 'collapse', 'apocalypse', 'ruins', 'survivors'],
      negativeSignals: ['stable futuristic utopia', 'pre-collapse institutional order'],
    },
    {
      slug: 'time-travel-science-fiction',
      name: 'Time Travel Science Fiction',
      description: 'Temporal displacement narratives exploring causality, paradox, and historical intervention.',
      canonicalThemes: ['causality loops', 'paradox', 'timeline revision'],
      commonKeywords: ['time travel', 'timeline', 'paradox', 'future self', 'time machine'],
      negativeSignals: ['static present-day realism', 'non-temporal fantasy portal'],
    },
    {
      slug: 'alternate-history-multiverse',
      name: 'Alternate History & Multiverse',
      description: 'Counterfactual worlds and branching realities that challenge historical or ontological singularity.',
      canonicalThemes: ['counterfactual history', 'parallel realities', 'branching worlds'],
      commonKeywords: ['alternate history', 'parallel universe', 'multiverse', 'dimension', 'counterfactual'],
      negativeSignals: ['single-world continuity without ontological branching', 'straight biography'],
    },
    {
      slug: 'artificial-intelligence-robotics',
      name: 'Artificial Intelligence & Robotics',
      description: 'Machine intelligence, synthetic agency, and human-robot relations as central speculative focus.',
      canonicalThemes: ['machine consciousness', 'human-AI ethics', 'synthetic personhood'],
      commonKeywords: ['artificial intelligence', 'robot', 'android', 'machine learning', 'sentience'],
      negativeSignals: ['technology as minor background prop', 'pure monster feature without AI premise'],
    },
    {
      slug: 'alien-contact-invasion',
      name: 'Alien Contact & Invasion',
      description: 'Extraterrestrial encounter cinema spanning first-contact diplomacy and hostile incursion.',
      canonicalThemes: ['otherness encounter', 'contact protocol', 'invasion paranoia'],
      commonKeywords: ['alien', 'extraterrestrial', 'first contact', 'invasion', 'ufo'],
      negativeSignals: ['earthbound drama with no extraterrestrial premise', 'pure mythic fantasy creatures'],
    },
    {
      slug: 'biopunk-genetic-engineering',
      name: 'Biopunk & Genetic Engineering',
      description: 'Biotech-centered speculation around cloning, engineered life, mutation, and biological governance.',
      canonicalThemes: ['biotechnology ethics', 'engineered species', 'mutation risk'],
      commonKeywords: ['genetic engineering', 'clone', 'mutation', 'biohacking', 'pathogen', 'lab'],
      negativeSignals: ['mechanical sci-fi without biological stakes', 'supernatural transformation lore'],
    },
    {
      slug: 'military-science-fiction',
      name: 'Military Science Fiction',
      description: 'Speculative warfare frameworks emphasizing doctrine, command systems, and militarized futures.',
      canonicalThemes: ['future warfare', 'command hierarchy', 'weaponized technology'],
      commonKeywords: ['fleet', 'soldier', 'combat', 'war zone', 'military', 'battalion'],
      negativeSignals: ['non-conflict philosophical chamber drama', 'civilian domestic comedy'],
    },
    {
      slug: 'science-fiction-horror',
      name: 'Science Fiction Horror',
      description: 'Hybrid mode where speculative premises intensify dread through contagion, body threat, or unknown entities.',
      canonicalThemes: ['containment breach', 'biological threat', 'cosmic dread'],
      commonKeywords: ['space horror', 'infection', 'xenomorph', 'containment', 'speculative terror'],
      negativeSignals: ['light family adventure tone', 'pure military action without horror affect'],
    },
    {
      slug: 'social-speculative-science-fiction',
      name: 'Social Speculative Science Fiction',
      description: 'Speculative narratives where social institutions and identity systems are the primary object of inquiry.',
      canonicalThemes: ['institutional critique', 'identity politics', 'social engineering'],
      commonKeywords: ['speculative society', 'social order', 'class system', 'identity regime', 'policy future'],
      negativeSignals: ['effects-first spectacle with minimal societal argument', 'monster-of-the-week plotting'],
    },
    {
      slug: 'new-weird-cosmic-science-fiction',
      name: 'New Weird & Cosmic Science Fiction',
      description: 'Contemporary boundary-pushing science fiction blending cosmic scale, ontological uncertainty, and surreal affect.',
      canonicalThemes: ['ontological instability', 'cosmic strangeness', 'epistemic uncertainty'],
      commonKeywords: ['new weird', 'cosmic', 'eldritch', 'surreal', 'anomaly', 'incomprehensible'],
      negativeSignals: ['strict procedural realism', 'formulaic techno-thriller without ontological stakes'],
    },
    {
      slug: 'retrofuturism-steampunk-dieselpunk',
      name: 'Retrofuturism, Steampunk & Dieselpunk',
      description: 'Alt-modern visual and technological imaginaries that reframe past eras through speculative futurity.',
      canonicalThemes: ['alternate modernity', 'anachronistic technology', 'industrial fantasy-science overlap'],
      commonKeywords: ['retrofuturism', 'steampunk', 'dieselpunk', 'clockwork', 'victorian future'],
      negativeSignals: ['present-day realism without retro-speculative frame', 'pure high fantasy court drama'],
    },
  ],
};
