import type { SeasonOntology } from '@/lib/ontology/types';

export const SEASON_2_CULT_CLASSICS_ONTOLOGY: SeasonOntology = {
  seasonId: 'season-2',
  seasonSlug: 'cult-classics',
  taxonomyVersion: 'season-2-cult-v3',
  nodes: [
    {
      slug: 'origins-of-cult-cinema',
      name: 'Origins of Cult Cinema',
      description: 'Foundations of cult reputation before codified midnight and VHS cultures.',
      canonicalThemes: ['proto-cult rediscovery', 'forbidden cinema', 'critical reevaluation'],
      commonKeywords: ['forbidden', 'underground', 'rediscovered', 'cult reputation'],
      negativeSignals: ['franchise tentpole', 'contemporary prestige blockbuster'],
    },
    {
      slug: 'midnight-movies',
      name: 'Midnight Movies',
      description: 'Counterculture theatrical circuit driven by repeat late-night screenings.',
      canonicalThemes: ['midnight screenings', 'audience ritual', 'counterculture'],
      commonKeywords: ['midnight movie', 'counterculture', 'underground', 'late-night'],
      negativeSignals: ['mainstream multiplex release', 'four-quadrant tentpole'],
    },
    {
      slug: 'grindhouse-exploitation',
      name: 'Grindhouse & Exploitation',
      description: 'Low-budget transgressive cinema tied to grindhouse, regional, and import circuits.',
      canonicalThemes: ['transgression', 'shock aesthetics', 'regional circuits', 'sleaze economy'],
      commonKeywords: ['grindhouse', 'exploitation', 'video nasty', 'sleaze', 'regional cult'],
      negativeSignals: ['family animation', 'prestige period drama'],
    },
    {
      slug: 'eurocult',
      name: 'Eurocult',
      description: 'European cult traditions including giallo-adjacent, transgressive art-horror, and exploitation hybrids.',
      canonicalThemes: ['continental transgression', 'arthouse-exploitation overlap', 'festival rediscovery'],
      commonKeywords: ['giallo', 'eurocult', 'italian exploitation', 'continental cult'],
      negativeSignals: ['mainstream studio period drama', 'safe prestige fare'],
    },
    {
      slug: 'psychotronic-cinema',
      name: 'Psychotronic Cinema',
      description: 'Wild, disreputable, and transgressive oddities canonized through fan communities.',
      canonicalThemes: ['psychotronic taste', 'outsider craft', 'video-era rediscovery'],
      commonKeywords: ['psychotronic', 'sleazy', 'trash cinema', 'midnight weirdness'],
      negativeSignals: ['high-budget prestige studio drama', 'awards-season biopic'],
    },
    {
      slug: 'cult-horror',
      name: 'Cult Horror',
      description: 'Core cult horror canon shaped by fandom, repertory revival, and home-video circulation.',
      canonicalThemes: ['horror fandom', 'practical effects obsession', 'franchise-adjacent cults'],
      commonKeywords: ['cult horror', 'video nasty', 'body horror', 'slasher cult'],
      negativeSignals: ['mainstream awards horror crossover', 'family horror'],
    },
    {
      slug: 'cult-science-fiction',
      name: 'Cult Science Fiction',
      description: 'Speculative cult canon shaped by midnight, repertory, and genre fan circuits.',
      canonicalThemes: ['speculative cult mythology', 'retro-futurist aesthetics', 'fandom canon'],
      commonKeywords: ['cult sci-fi', 'retro futurist', 'dystopian cult', 'genre fandom'],
      negativeSignals: ['contemporary franchise blockbuster', 'four-quadrant superhero'],
    },
    {
      slug: 'outsider-cinema',
      name: 'Outsider Cinema',
      description: 'Counter-institutional films rooted in outsider authorship and subcultural circulation.',
      canonicalThemes: ['outsider authorship', 'DIY rebellion', 'counter-institutional aesthetics'],
      commonKeywords: ['outsider', 'underground', 'counterculture', 'DIY'],
      negativeSignals: ['institutional prestige', 'studio franchise IP'],
    },
    {
      slug: 'camp-cult-comedy',
      name: 'Camp & Cult Comedy',
      description: 'Camp, absurdist, and offbeat comedies canonized by repeat-viewing communities.',
      canonicalThemes: ['camp ritual', 'quote culture', 'midnight laughter'],
      commonKeywords: ['camp', 'offbeat comedy', 'cult comedy', 'quote-along'],
      negativeSignals: ['straight mainstream romcom', 'awards prestige comedy'],
    },
    {
      slug: 'video-store-era',
      name: 'Video Store Era',
      description: 'VHS rental culture that created shelf-discovery cult canon.',
      canonicalThemes: ['rental-era canon', 'cover-art discovery', 'late-night cable'],
      commonKeywords: ['vhs', 'video store', 'rental cult', 'direct-to-video'],
      negativeSignals: ['post-streaming prestige original', 'modern tentpole launch'],
    },
    {
      slug: 'modern-cult-phenomena',
      name: 'Modern Cult Phenomena',
      description: 'Late-20th/early-21st century cult formations accelerated by online fandom and rediscovery.',
      canonicalThemes: ['meme-era rediscovery', 'online fandom', 'long-tail canonization'],
      commonKeywords: ['internet cult', 'meme', 'rediscovered', 'fandom', 'festival breakout'],
      negativeSignals: ['algorithmic blockbuster', 'family animation franchise'],
    },
  ],
};
