import type { SeasonOntology } from '@/lib/ontology/types';

export const SEASON_3_SCI_FI_ONTOLOGY: SeasonOntology = {
  seasonId: 'season-3',
  seasonSlug: 'sci-fi',
  taxonomyVersion: 'season-3-sci-fi-v2',
  nodes: [
    {
      slug: 'proto-science-fiction',
      name: 'Proto Science Fiction',
      description: 'Early speculative cinema foundations from silent-era futurism through pre-space-age thought experiments — the industrial imagination before atomic anxiety.',
      canonicalThemes: ['industrial modernity', 'scientific hubris', 'future societies', 'mechanical man'],
      commonKeywords: ['silent', 'futurist', 'mad scientist', 'automaton', 'utopia', 'metropolis', 'frankenstein', 'invisible'],
      negativeSignals: ['pure contemporary action franchise', 'historical drama without speculative premise'],
      typicalEra: ['1900s', '1910s', '1920s', '1930s', '1940s'],
      orderIndex: 1,
      canonAnchors: [
        { title: 'Metropolis', year: 1927 },
        { title: 'Frankenstein', year: 1931 },
        { title: 'Things to Come', year: 1936 },
        { title: 'The Invisible Man', year: 1933 },
        { title: 'Dr. Jekyll and Mr. Hyde', year: 1931 },
      ],
    },
    {
      slug: 'atomic-age-science-fiction',
      name: 'Atomic Age Sci-Fi',
      description: 'Post-Hiroshima radiation anxiety expressed through giant creatures, alien visitors, and science-gone-wrong — cinema processing the terror of nuclear power.',
      canonicalThemes: ['nuclear anxiety', 'radiation mutation', 'science out of control', 'threat from above'],
      commonKeywords: ['atomic', 'radiation', 'nuclear', 'giant', 'mutation', 'bomb', 'experiment gone wrong'],
      negativeSignals: ['pre-nuclear setting', 'pure fantasy without scientific premise', 'contemporary domestic comedy'],
      typicalEra: ['1950s', '1960s'],
      orderIndex: 2,
      canonAnchors: [
        { title: 'The Day the Earth Stood Still', year: 1951 },
        { title: 'Forbidden Planet', year: 1956 },
        { title: 'Them!', year: 1954 },
        { title: 'Creature from the Black Lagoon', year: 1954 },
        { title: 'The Thing from Another World', year: 1951 },
      ],
    },
    {
      slug: 'cold-war-paranoia',
      name: 'Cold War Paranoia',
      description: 'Speculative films driven by ideological suspicion, infiltration, and civilizational stakes — body snatchers, doomsday machines, and contamination as political metaphor.',
      canonicalThemes: ['ideological infiltration', 'mass conformity', 'mutually assured destruction', 'institutional distrust'],
      commonKeywords: ['infiltration', 'conformity', 'doomsday', 'conspiracy', 'contamination', 'red scare', 'pod', 'spy'],
      negativeSignals: ['optimistic exploratory adventure', 'post-cold-war setting without period anxiety'],
      typicalEra: ['1950s', '1960s', '1970s'],
      orderIndex: 3,
      canonAnchors: [
        { title: 'Invasion of the Body Snatchers', year: 1956 },
        { title: 'Dr. Strangelove', year: 1964 },
        { title: 'The Manchurian Candidate', year: 1962 },
        { title: 'The Andromeda Strain', year: 1971 },
        { title: 'Fail Safe', year: 1964 },
      ],
    },
    {
      slug: 'space-race-cinema',
      name: 'Space Race Cinema',
      description: 'Cinema inspired by the moon shot era — cosmic voyages, first encounters with deep time, and the existential weight of leaving Earth.',
      canonicalThemes: ['cosmic scale', 'human insignificance', 'exploration', 'interplanetary societies', 'technological transcendence'],
      commonKeywords: ['space', 'astronaut', 'orbital', 'mission', 'planet', 'evolution', 'monolith', 'galaxy'],
      negativeSignals: ['earthbound setting without space premise', 'pre-spaceflight nostalgic piece'],
      typicalEra: ['1960s', '1970s'],
      orderIndex: 4,
      canonAnchors: [
        { title: '2001: A Space Odyssey', year: 1968 },
        { title: 'Planet of the Apes', year: 1968 },
        { title: 'Solaris', year: 1972 },
        { title: 'Silent Running', year: 1972 },
        { title: 'Marooned', year: 1969 },
      ],
    },
    {
      slug: 'new-hollywood-science-fiction',
      name: 'New Hollywood Sci-Fi',
      description: 'Counterculture-era science fiction — auteur-driven, anti-establishment, and formally adventurous. Dystopian societies and broken utopias as critique of the American dream.',
      canonicalThemes: ['systemic oppression', 'counterculture rebellion', 'state control', 'consumerism critique'],
      commonKeywords: ['dystopia', 'conformity', 'conditioning', 'state', 'food', 'population', 'control'],
      negativeSignals: ['studio blockbuster optimism', 'pre-1960s period setting without retro-speculative frame'],
      typicalEra: ['1970s'],
      orderIndex: 5,
      canonAnchors: [
        { title: 'THX 1138', year: 1971 },
        { title: 'A Clockwork Orange', year: 1971 },
        { title: 'Soylent Green', year: 1973 },
        { title: 'Zardoz', year: 1974 },
        { title: "Logan's Run", year: 1976 },
      ],
    },
    {
      slug: 'philosophical-science-fiction',
      name: 'Philosophical Sci-Fi',
      description: 'Introspective, contemplative speculative cinema where ideas outpace plot — meditations on identity, consciousness, memory, and what it means to be human.',
      canonicalThemes: ['consciousness', 'identity dissolution', 'memory and perception', 'the unknowable other'],
      commonKeywords: ['identity', 'consciousness', 'memory', 'perception', 'self', 'mind', 'reality', 'existential'],
      negativeSignals: ['action-first spectacle with no philosophical dimension', 'monster-of-the-week plotting'],
      typicalEra: ['1970s', '1980s', '1990s'],
      orderIndex: 6,
      canonAnchors: [
        { title: 'Stalker', year: 1979 },
        { title: 'The Man Who Fell to Earth', year: 1976 },
        { title: 'Altered States', year: 1980 },
        { title: 'Liquid Sky', year: 1982 },
        { title: 'Under the Skin', year: 2013 },
      ],
    },
    {
      slug: 'blockbuster-science-fiction',
      name: 'Blockbuster Sci-Fi',
      description: 'The Hollywood era of genre-defining spectacle — mythic heroes, practical effects, and the summer blockbuster as cultural event.',
      canonicalThemes: ['mythic heroism', 'galactic stakes', 'creature threat', 'technological wonder'],
      commonKeywords: ['star', 'wars', 'empire', 'rebellion', 'alien', 'close encounters', 'terminator', 'force'],
      negativeSignals: ['low-budget European art cinema', 'quiet chamber drama without spectacle dimension'],
      typicalEra: ['1970s', '1980s'],
      orderIndex: 7,
      canonAnchors: [
        { title: 'Star Wars', year: 1977 },
        { title: 'Close Encounters of the Third Kind', year: 1977 },
        { title: 'Alien', year: 1979 },
        { title: 'E.T. the Extra-Terrestrial', year: 1982 },
        { title: 'The Terminator', year: 1984 },
        { title: 'RoboCop', year: 1987 },
      ],
    },
    {
      slug: 'cyberpunk',
      name: 'Cyberpunk',
      description: 'High-tech / low-life futures focused on networked systems, corporate power, and urban decay — noir aesthetics fused with technological dystopia.',
      canonicalThemes: ['corporate dystopia', 'networked identity', 'augmented bodies', 'surveillance capitalism'],
      commonKeywords: ['cyberpunk', 'hacker', 'megacorp', 'cyberspace', 'neon', 'implant', 'replicant', 'matrix'],
      negativeSignals: ['pastoral rural setting without technological mediation', 'pre-digital historical setting'],
      typicalEra: ['1980s', '1990s', '2000s'],
      orderIndex: 8,
      canonAnchors: [
        { title: 'Blade Runner', year: 1982 },
        { title: 'Tron', year: 1982 },
        { title: 'Akira', year: 1988 },
        { title: 'Ghost in the Shell', year: 1995 },
        { title: 'The Matrix', year: 1999 },
      ],
    },
    {
      slug: 'ai-cinema',
      name: 'AI Cinema',
      description: 'Machine intelligence, synthetic agency, and human-AI relations as central speculative focus — from chess-playing computers to emergent personhood.',
      canonicalThemes: ['machine consciousness', 'human-AI ethics', 'synthetic personhood', 'technological dependency'],
      commonKeywords: ['artificial intelligence', 'robot', 'android', 'machine learning', 'sentience', 'hal', 'samantha', 'ava'],
      negativeSignals: ['technology as minor background prop', 'pure monster feature without AI premise'],
      orderIndex: 9,
      canonAnchors: [
        { title: 'WarGames', year: 1983 },
        { title: 'A.I. Artificial Intelligence', year: 2001 },
        { title: 'Her', year: 2013 },
        { title: 'Ex Machina', year: 2014 },
        { title: 'Colossus: The Forbin Project', year: 1970 },
      ],
    },
    {
      slug: 'alien-encounter',
      name: 'Alien Encounter',
      description: 'Extraterrestrial contact cinema spanning first-contact diplomacy, hostile incursion, and the philosophical stakes of meeting the other.',
      canonicalThemes: ['otherness encounter', 'contact protocol', 'invasion paranoia', 'interspecies communication'],
      commonKeywords: ['alien', 'extraterrestrial', 'first contact', 'invasion', 'ufo', 'signal', 'arrival', 'district'],
      negativeSignals: ['earthbound drama with no extraterrestrial premise', 'pure mythic fantasy creatures'],
      orderIndex: 10,
      canonAnchors: [
        { title: 'The Thing', year: 1982 },
        { title: 'Contact', year: 1997 },
        { title: 'District 9', year: 2009 },
        { title: 'Arrival', year: 2016 },
        { title: 'Enemy Mine', year: 1985 },
      ],
    },
    {
      slug: 'time-travel',
      name: 'Time Travel',
      description: 'Temporal displacement narratives exploring causality, paradox, and historical intervention — from comedic high-concept to hard-edged bootstrap paradoxes.',
      canonicalThemes: ['causality loops', 'paradox', 'timeline revision', 'bootstrap narrative'],
      commonKeywords: ['time travel', 'timeline', 'paradox', 'future self', 'time machine', 'loop', 'back to the future'],
      negativeSignals: ['static present-day realism', 'non-temporal fantasy portal', 'purely spatial dimension hopping'],
      orderIndex: 11,
      canonAnchors: [
        { title: 'Back to the Future', year: 1985 },
        { title: '12 Monkeys', year: 1995 },
        { title: 'Primer', year: 2004 },
        { title: 'Looper', year: 2012 },
        { title: 'The Terminator', year: 1984 },
      ],
    },
    {
      slug: 'modern-speculative',
      name: 'Modern Speculative',
      description: 'Contemporary science fiction that trades spectacle for rigour — character-driven, scientifically grounded, and concerned with urgent near-future realities.',
      canonicalThemes: ['near-future realism', 'civilizational stakes', 'scientific awe', 'societal collapse'],
      commonKeywords: ['speculative', 'near future', 'climate', 'humanity', 'survival', 'interstellar', 'annihilation'],
      negativeSignals: ['pure escapist fantasy', 'period piece without contemporary resonance'],
      orderIndex: 12,
      canonAnchors: [
        { title: 'Children of Men', year: 2006 },
        { title: 'Moon', year: 2009 },
        { title: 'Gravity', year: 2013 },
        { title: 'Interstellar', year: 2014 },
        { title: 'Annihilation', year: 2018 },
      ],
    },
  ],
};
